### PR TITLE
Ensure Polymer 3 Modulizer compatibility

### LINKED ISSUE #35: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #35

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/36)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[package.json, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/36#-L8GV3-zwJrTFmrQSHUz:-L8GV3-zwJrTFmrQSHV-:bgv2vfi) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/a24ee0495d51e087e7030dd3ea591a7ddabb9b4a/package.json#L24)):*
> ```JSON
>   },
>   "devDependencies": {
>     "proto-tasks": "git://github.com/tomivirkki/proto-tasks.git#master"
> ```

I feel like this proto-tasks -thing (trying to centralize the devDependencies & tasks) needs more thinking. It's not related to the project at hand but rather an optimization so let's create a separate issue for it and handle it later. So for now, let's revert to this file and use the local gulpfile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/36)*

**Comment by web-padawan** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-control-state-mixin/36#-L8GV3-zwJrTFmrQSHUz:-L8GkAWX9hC8bemzcy3d:bp3aow6) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/a24ee0495d51e087e7030dd3ea591a7ddabb9b4a/package.json#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I feel like this proto-tasks -thing (trying to centralize the devDependencies & tasks) needs more thinking. It's not related to the project at hand but rather an optimization so let's create a separate issue for it and handle it later. So for now, let's revert to this file and use the local gulpfile.
</blockquote></details>

Reverted.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-control-state-mixin/36)*

**Comment by yuriy-fix** [comment]
:lgtm: 

---

Reviewed 5 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/36#-:-L8WNrLC2uMTosF1nuFY:bg7igkv)*

**Comment by tomivirkki** [comment]
*[.travis.yml, line 15 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-control-state-mixin/36#-L8WhEm48_27VQ5ZVnUg:-L8WhEm48_27VQ5ZVnUh:ba5u0tf) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/90adf1352bec8966474c54f3d40167bc9630c38f/.travis.yml#L15)):*
> ```YAML
> 
> before_script:
>   - npm install bower polymer-cli@next -g
> ```

Should we not use `@next` for now?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-control-state-mixin/36)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 15 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/36#-L8WhEm48_27VQ5ZVnUg:-L8WigobOzwzQP2BAh4J:buziwhl) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/90adf1352bec8966474c54f3d40167bc9630c38f/.travis.yml#L15)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should we not use `@next` for now?
</blockquote></details>

Not using `@next` would result in errors like this:

```
Failed to resolve module specifier "@polymer/polymer/polymer-legacy.js". Relative references must start with either "/", "./", or "../".
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/36)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/36#-:-L8Wv2qER6FmDDk83Tjq:bnfp4nl)*

**Pull request merged**
