### PR TITLE
Change API so as focused is only an attribute

### LINKED ISSUE #23: Add a demo page with components
Add a demo page with all the components that use this as a dependency so it's easy to test them during development.

### LINKED ISSUE #26: Deprecate `focused` property
The focused state should not end up in public API.

Instead `(document || shadowRoot).activeElement` standard DOM API should be used to find focused element. Focus change notification triggers standard focus events.

Include https://github.com/vaadin/vaadin-control-state-mixin/issues/23

### PR DESCRIPTION
**Pull request by manolo**
Fixes #26
Fixes #23 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/27)

### CODE REVIEW

**Comment by platosha** [comment]
This is great, but too soon. Affects `<vaadin-text-field>` API, therefore requires a major version release of that.

The issue says “deprecate”, but not “remove” just yet.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-:-KvlVCv4t4XhQLZVZBbi:bx42f2m)*

**Comment by platosha** [comment]
BTW was suggested to also include #23 here.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-:-KvlVpGXqj2ccWnYpb-H:b-hw6ake)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by platosha** [comment]
:lgtm_cancel: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-:-KvlW3P1YcnocNeorrgc:b8b79qu)*

**Comment by manolo** [comment]
What do you mean in text-field ? it does not uses the property, but the attribute, the attribute remains. Or am I missing something ? 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-:-KvlZq8fHWEpyGpJynz3:b-t2jhs8)*

**Comment by platosha** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-control-state-mixin.html, line 56 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-KvlgT_s8EXeLh3qScQW:-KvlgT_s8EXeLh3qScQX:bioykrv) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/74ba94f01737c6c28646359d9cec357d5714fb72/vaadin-control-state-mixin.html#L56)):*
> ```HTML
> 
>         /* @deprecated will be removed in next major version */
>         focused: Boolean,
> ```

Well... could you rollback the declaration please? There was much more: readOnly, notify...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-control-state-mixin.html, line 56 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-KvlgT_s8EXeLh3qScQW:-Kvm1MB2PrRsl44U4Brd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/74ba94f01737c6c28646359d9cec357d5714fb72/vaadin-control-state-mixin.html#L56)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Well... could you rollback the declaration please? There was much more: readOnly, notify...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by manolo** [comment]
@platosha demos for #23 included in this PR as well

---

Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-:-KvmDLWOQd8AClOJRU8G:bfm0gzx)*

**Comment by limonte** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[demo/index.html, line 35 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw-1Yqe71kjfkzTU6jE:-Kw-1Yqe71kjfkzTU6jF:b-io4d7e) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/09af1c942b9435b66f06c631f02a5b0d84fb1715/demo/index.html#L35)):*
> ```HTML
> 
>     <h3>vaadin-text-field</h3>
>     <vaadin-text-field tabindex="1">TabIndex 1</vaadin-text-field>
> ```

`TabIndex 1` should be `label` or `placeholder`, otherwise it's not visible. The same for all text-fileds and password-fields below.

---

*[demo/index.html, line 55 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw-1hY70YhGlGFC8IPB:-Kw-1hY70YhGlGFC8IPC:bjoq2qj) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/09af1c942b9435b66f06c631f02a5b0d84fb1715/demo/index.html#L55)):*
> ```HTML
>     <vaadin-combo-box tabindex="1" placeholder="TabIndex 1" items='[1, 2, 3]'></vaadin-combo-box>
>     <vaadin-combo-box tabindex="3" placeholder="TabIndex 3" items='[1, 2, 3]'></vaadin-combo-box>
>     <vaadin-combo-box tabindex="2" placeholder="TabIndex 2 disabled" items='[1, 2, 3]'></vaadin-combo-box>
> ```

Placeholder says that this combo-box is disabled, but the `disabled` property isn't set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/index.html, line 35 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw-1Yqe71kjfkzTU6jE:-Kw4DD8gr4vrT7idu9p4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/09af1c942b9435b66f06c631f02a5b0d84fb1715/demo/index.html#L35)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

`TabIndex 1` should be `label` or `placeholder`, otherwise it's not visible. The same for all text-fileds and password-fields below.
</blockquote></details>

Done.

---

*[demo/index.html, line 55 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw-1hY70YhGlGFC8IPB:-Kw4DDcECJ6I-cHb06Nv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/09af1c942b9435b66f06c631f02a5b0d84fb1715/demo/index.html#L55)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Placeholder says that this combo-box is disabled, but the `disabled` property isn't set.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by tomivirkki** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 57 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw4EUXjnoRYSmfZTCDv:-Kw4EUXjnoRYSmfZTCDw:b-ooq2gs) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f6756870820e47d60241fd7a8203ec9cda6a40ba/vaadin-control-state-mixin.html#L57)):*
> ```HTML
>         /**
>          * If true, the element currently has focus.
>          * Use this attribute for CSS rules when styling the element.
> ```

Remove this sentence. 
1. "this" is not an attribute
2. Control state mixin should not have an opinion on what the attribute should be used for. Its use is not limited to styling.

---

*[vaadin-control-state-mixin.html, line 59 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw4EusSPDJzP8_SG5-i:-Kw4EusSPDJzP8_SG5-j:bxu581e) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f6756870820e47d60241fd7a8203ec9cda6a40ba/vaadin-control-state-mixin.html#L59)):*
> ```HTML
>          * Use this attribute for CSS rules when styling the element.
>          *
>          * @deprecated this property will not be accessible in the next major version
> ```

The `@deprecated` annotation does nothing. If I use this mixin in `<vaadin-button>` for example and run analysis, `focused` property is documented just as before without any deprecation info. Maybe `@protected` or even `@private`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 57 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw4EUXjnoRYSmfZTCDv:-Kw5QThsNH26JROw9Bsl:bsddcqd) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f6756870820e47d60241fd7a8203ec9cda6a40ba/vaadin-control-state-mixin.html#L57)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Remove this sentence. 
1. "this" is not an attribute
2. Control state mixin should not have an opinion on what the attribute should be used for. Its use is not limited to styling.
</blockquote></details>

This is both a property and an attribute, the attribute is used for CSS'ing that was the sentence about.

The point here is that we still want to maintain the attribute support in the API but not the property, that is what we should say in some way.

---

*[vaadin-control-state-mixin.html, line 59 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw4EusSPDJzP8_SG5-i:-Kw5QpASnU7JrPPqm021:b-7fyajx) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f6756870820e47d60241fd7a8203ec9cda6a40ba/vaadin-control-state-mixin.html#L59)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The `@deprecated` annotation does nothing. If I use this mixin in `<vaadin-button>` for example and run analysis, `focused` property is documented just as before without any deprecation info. Maybe `@protected` or even `@private`?
</blockquote></details>

But the deprecated sentence should be shown, isn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by tomivirkki** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 57 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw4EUXjnoRYSmfZTCDv:-Kw5foExDWBSs-CpUYKJ:b93hsun) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f6756870820e47d60241fd7a8203ec9cda6a40ba/vaadin-control-state-mixin.html#L57)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This is both a property and an attribute, the attribute is used for CSS'ing that was the sentence about.

The point here is that we still want to maintain the attribute support in the API but not the property, that is what we should say in some way.
</blockquote></details>

Just document the state attribute the same way as we do in every element. We don't document attributes in property documentation.

---

*[vaadin-control-state-mixin.html, line 59 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw4EusSPDJzP8_SG5-i:-Kw5gMkjSrmOIkjSAJzv:bcgoc6r) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f6756870820e47d60241fd7a8203ec9cda6a40ba/vaadin-control-state-mixin.html#L59)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

But the deprecated sentence should be shown, isn't it?
</blockquote></details>

Try it yourself. I don't see it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by manolo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 57 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw4EUXjnoRYSmfZTCDv:-Kw5mhmtaAkWlqdME-C9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f6756870820e47d60241fd7a8203ec9cda6a40ba/vaadin-control-state-mixin.html#L57)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Just document the state attribute the same way as we do in every element. We don't document attributes in property documentation.
</blockquote></details>

Done.

---

*[vaadin-control-state-mixin.html, line 59 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw4EusSPDJzP8_SG5-i:-Kw5mi6n3GFMCdfaXrno:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f6756870820e47d60241fd7a8203ec9cda6a40ba/vaadin-control-state-mixin.html#L59)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Try it yourself. I don't see it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by manolo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 59 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-Kw4EusSPDJzP8_SG5-i:-Kw5morRxpAkOwezryx3:b5vbtb5) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f6756870820e47d60241fd7a8203ec9cda6a40ba/vaadin-control-state-mixin.html#L59)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Anything after an empty line, or after a line starting with `@` is ignored by the analyser. 
Leaving the `@deprecated` inside the sentence so as it's maintained in documentation, the `@` makes sense for developers when reading, so leaving it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-:-Kw9Ul0iGR6Kh2SktQ4h:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/27#-:-Kw9Wk2EWvt6ITxM_XgE:bnfp4nl)*

**Pull request merged**
