### PR TITLE
P3 preview

### PR DESCRIPTION
**Pull request by manolo**
Connects to https://github.com/vaadin/components-team-tasks/issues/368

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/39)

### CODE REVIEW

**Comment by manolo** [comment]
:lgtm: 

---

Reviewed 2 of 8 files at r1, 1 of 2 files at r2, 2 of 4 files at r3, 3 of 3 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/39#-:-LFMwlxoDLK4MJAJf77O:bg7igkv)*

**Comment by tomivirkki** [comment]
*[package.json, line 3 at r5](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/39#-LFN9ma26k0l-N0zUQtI:-LFN9ma26k0l-N0zUQtJ:b-ibqdj0) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/11a48f1799ca4e85d63c854866827a2e94fa3954/package.json#L3)):*
> ```JSON
> {
>   "name": "@vaadin/vaadin-control-state-mixin",
>   "version": "2.0.3-pre.4",
> ```

The version shouldn't change

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/39)*

**Comment by manolo** [comment]
Review status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @manolo and @tomivirkki)

---

*[package.json, line 3 at r5](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/39#-LFN9ma26k0l-N0zUQtI:-LFNX1u28MuOG_O0mKJc:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/11a48f1799ca4e85d63c854866827a2e94fa3954/package.json#L3)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The version shouldn't change
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/39)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 8 files at r1, 1 of 2 files at r2, 2 of 4 files at r3, 2 of 3 files at r5, 1 of 1 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/39#-:-LFR20pe6psbuLdTKmFu:bnfp4nl)*

**Pull request merged**
