### PR TITLE
Don't focus element that hasn't yet been attached to the DOM

### PR DESCRIPTION
**Pull request by samiheikki**
Connects to https://github.com/vaadin/vaadin-text-field/issues/269

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/47)

### CODE REVIEW

**Review by yuriy-fix — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/47#-:-LQZFAAg5FpT6g6HvMxP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by tomivirkki** [comment]
___
*[vaadin-control-state-mixin.html, line 208 at r1](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/47#-LQcS5tCCydd8xnoTQAA:-LQcS5tCCydd8xnoTQAB:bjk3yu6) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/274282fe11a4865510575862efd4e5688f0b8359/vaadin-control-state-mixin.html#L208)):*
> ```HTML
>      */
>     focus() {
>       if (!this.focusElement || this.disabled) {
> ```

Why no test for this?

**Comment by yuriy-fix** [comment]
Merged to https://github.com/vaadin/vaadin-control-state-mixin/tree/new-element-focus. Will implement suggestion from there.

**Comment by yuriy-fix** [comment]
___
*[vaadin-control-state-mixin.html, line 208 at r1](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/47#-LQcS5tCCydd8xnoTQAA:-LQdIhun-pBjHir4dKK_:bfvamlj) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/274282fe11a4865510575862efd4e5688f0b8359/vaadin-control-state-mixin.html#L208)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why no test for this?
</blockquote></details>

Added here: https://github.com/vaadin/vaadin-control-state-mixin/pull/48

**Pull request merged**
