### PR TITLE
Set focus-ring for autofocused elements

### PR DESCRIPTION
**Pull request by limonte**
---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/15)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-control-state-mixin.html, line 70 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15#-KsdDCnVSS5TAUg26Xfw:-KsdDCnW8NvWhLBUUGHj:b-ixtkci) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/45fb6eb39943e261f81bd474db5e5a699faf074a/vaadin-control-state-mixin.html#L70)):*
> ```HTML
>          * A11ycasts: https://youtu.be/ilj2P5-5CjI
>          */
>         focusRing: {
> ```

Why the new property?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-control-state-mixin.html, line 70 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15#-KsdDCnVSS5TAUg26Xfw:-KsdDunjLXHCZ9Syir5X:b-t7nrsw) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/45fb6eb39943e261f81bd474db5e5a699faf074a/vaadin-control-state-mixin.html#L70)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why the new property?
</blockquote></details>

To get rid of `setAttribute()` `getAttribute()` `hasAttribute`. Any reasons why not to introduce it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15)*

**Comment by tomivirkki** [comment]
*[vaadin-control-state-mixin.html, line 70 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15#-KsdDCnVSS5TAUg26Xfw:-KsdE9YXAEm506Jg8mbW:b2zl4uf) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/45fb6eb39943e261f81bd474db5e5a699faf074a/vaadin-control-state-mixin.html#L70)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

To get rid of `setAttribute()` `getAttribute()` `hasAttribute`. Any reasons why not to introduce it?
</blockquote></details>

Yes. This is adding new API (new property). We only need the attribute. There's nothing wrong with using `setAttribute()` etc. #usetheplatform

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-control-state-mixin.html, line 70 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15#-KsdDCnVSS5TAUg26Xfw:-KsdFM-cBX6W6GcXWtIM:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/45fb6eb39943e261f81bd474db5e5a699faf074a/vaadin-control-state-mixin.html#L70)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Yes. This is adding new API (new property). We only need the attribute. There's nothing wrong with using `setAttribute()` etc. #usetheplatform
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15)*

**Comment by tomivirkki** [comment]
*[vaadin-control-state-mixin.html, line 108 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15#-Kshy48m1oxk9QqjjTdZ:-Kshy48m1oxk9QqjjTd_:byj7c7l) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/41d0f9c203ad00cafd167496ccde799397156036/vaadin-control-state-mixin.html#L108)):*
> ```HTML
>         window.requestAnimationFrame(() => {
>           this._focus();
>           this.setAttribute('focus-ring', '');
> ```

This PR adds `focus-ring` attribute to an `autofocus` button. Why is it connected to vaadin/vaadin-button#32 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-control-state-mixin.html, line 108 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15#-Kshy48m1oxk9QqjjTdZ:-Ksi1NLvTB5NNSrEnHqN:b-pwvi06) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/41d0f9c203ad00cafd167496ccde799397156036/vaadin-control-state-mixin.html#L108)):*
>  to an autofocus button

To any `autofocus`'ed elements, button in particular.

 > Why is it connected to vaadin/vaadin-button#32 ?

Disconnected now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/15#-:-Ksi3bd07BhJBrE0J20u:bnfp4nl)*

**Pull request merged**
