### PR TITLE
When keydown event is default prevented, should ignore it

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/vaadin-date-picker/issues/477

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/28)

### CODE REVIEW

**Comment by web-padawan** [comment]
Tests failing in Edge. Also, need to update Safari to 11.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-control-state-mixin.html, line 107 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/28#-KzheRS1sOVq4S9kFmwI:-KzheRS1sOVq4S9kFmwJ:b-c2tboa) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f8639c020b470f4cb2aa41341d434fcb4f0ae23c/vaadin-control-state-mixin.html#L107)):*
> ```HTML
> 
>       this.addEventListener('keydown', e => {
>         if (!e.defaultPrevented) {
> ```

BTW this could be refactored to use single `if` statement unless we expect other logic here. Not a blocker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/28#-:-KzheLxVj9im4WWi8ggt:b19w0vm)*

**Comment by manolo** [comment]
Fixed tests

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-control-state-mixin.html, line 107 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/28#-KzheRS1sOVq4S9kFmwI:-KznBBR6rU1NprhGom--:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/f8639c020b470f4cb2aa41341d434fcb4f0ae23c/vaadin-control-state-mixin.html#L107)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW this could be refactored to use single `if` statement unless we expect other logic here. Not a blocker.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/28#-:-KznB91pbl1UeftQNnNj:b1b5mi8)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/28#-:-Kznuse3zA5qtcltWbkv:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/28#-:-Kzo8eZqU4PSVg5Li-wA:bnfp4nl)*

**Pull request merged**
