### PR TITLE
Make preventable focus on mousedown instead of on click

### PR DESCRIPTION
**Pull request by platosha**
Reasoning: native mouse focus happens after mousedown. Preventing
mousedown default action on a focusable element results in disabling the
mouse focus.

Before this change, focus on host click was used, no way of preventing
this click focus was available.

See also: vaadin/vaadin-grid#878 vaadin/vaadin-grid#960
vaadin/vaadin-combo-box#503

Possibly conflicts with vaadin/vaadin-combo-box#507

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/17)

### CODE REVIEW

**Comment by platosha** [comment]
JSbin demo of preventing native focus with mousedown listener: http://jsbin.com/qesimamepa/edit?html,output

**Comment by limonte** [comment]
Please fix linter errors and tests.

**Comment by limonte** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/control-state.html, line 200 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17#-KtMkczG1699jVW-tTT7:-KtMkczG1699jVW-tTT8:bqgjbin) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/4de3afc5efedf3084e8ee31645d9d19952947be5/test/control-state.html#L200)):*
> ```HTML
>         it('should not set focused attribute on host click', () => {
>           customElement.click();
>           expect(customElement.focused).to.be.undefined;
> ```

@manolo should we maybe have a default value `false` for the `focused` property?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17#-:-KtMkzzbyUDej2XwbuhB:bnfp4nl)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/control-state.html, line 200 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17#-KtMkczG1699jVW-tTT7:-KtMl7FMjSw799YnP0B1:bynbsrq) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/4de3afc5efedf3084e8ee31645d9d19952947be5/test/control-state.html#L200)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

@manolo should we maybe have a default value `false` for the `focused` property?
</blockquote></details>

focused is not part of the component API but CSS api, so I don't see the need like other attributes we use for styling.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17)*

**Comment by manolo** [comment]
Seems that I pushed very soon the lgtm, when one of the CI builds set the review in green.
Apparently in IE click activates focus, and was detected in the complete build.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17#-:-KtMlduQwuXgFId0ig0G:b-u2x7r)*

**Comment by platosha** [comment]
The tests are fixed. @manolo @limonte acks please.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17#-:-KtQze2LEHmlsnf4QV5Q:bwdr5r3)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17#-:-KtR0CLOd_gX6sCVbAPO:bnfp4nl)*

**Comment by limonte** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17#-:-KtR3KH3gCc4Jc7OA-NG:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/17)*

**Pull request merged**
