### PR TITLE
Add vaadin-control-state-mixin

### PR DESCRIPTION
**Pull request by Saulis**
Connects to https://github.com/vaadin/components-team-tasks/issues/243

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-control-state-mixin/1)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-Xq9hxaKlDGG27_l8:-Ki-Xq9hxaKlDGG27_l9:benxa7x) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/5ac66f5c5d797b06ae56ef6e80990e48728c7979/package.json#L24)):*
> ```JSON
>   },
>   "devDependencies": {
>     "gemini": "^4.17.1",
> ```

No need for gemini / lighthouse devDependencies

---

*[README.md, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-YHRZqtbwXt93bQpa:-Ki-YHRZqtbwXt93bQpb:b-cw2sgp) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/5ac66f5c5d797b06ae56ef6e80990e48728c7979/README.md#L16)):*
> ```Markdown
> 
> 
> ## Running demos and tests in browser
> ```

Remove mentions of demos

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1)*

**Comment by Saulis** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-Xq9hxaKlDGG27_l8:-Ki-ZdxtbvVskQMe3yNT:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/5ac66f5c5d797b06ae56ef6e80990e48728c7979/package.json#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

No need for gemini / lighthouse devDependencies
</blockquote></details>

Done.

---

*[README.md, line 16 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-YHRZqtbwXt93bQpa:-Ki-ZeVmu5GxSujYXPfB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/5ac66f5c5d797b06ae56ef6e80990e48728c7979/README.md#L16)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Remove mentions of demos
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-:-Ki-a-V3PEX6qwy8Qhhn:bnfp4nl)*

**Comment by manolo** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[.eslintrc.json, line 15 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-b7IZnD9LtUj3L0Dd:-Ki-b7IZnD9LtUj3L0De:b-jhmxmd) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/516576e17958c707bd9c63a4ed4f56bcd7b1d601/.eslintrc.json#L15)):*
> ```JSON
>     "Vaadin": false
>   }
> }
> ```

I think you should add a NL at the end o all these files

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1)*

**Comment by manolo** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 5 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-bSbZ60vjz5Q1gcix:-Ki-bSbZ60vjz5Q1gciy:bje5edc) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/516576e17958c707bd9c63a4ed4f56bcd7b1d601/README.md#L5)):*
> ```Markdown
> [Gitter](https://gitter.im/vaadin/vaadin-core-elements?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
> 
> # vaadin-control-state-mixin
> ```

Please add some description about what this component is here.
I think we should notice the user that is a mixin used in vaadin components and API could change without advise.

---

*[README.md, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-bsePgP0PrybH849l:-Ki-bsePgP0PrybH849m:b-dr2ze3) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/516576e17958c707bd9c63a4ed4f56bcd7b1d601/README.md#L24)):*
> ```Markdown
> 1. You can also open in-browser tests by adding **test** to the URL, for example:
> 
>   - http://127.0.0.1:8080/components/vaadin-control-state-mixin/test
> ```

Some times URLs without ending are redirected to local folder. I think it's better to end the url with '/index.html'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1)*

**Comment by Saulis** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[.eslintrc.json, line 15 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-b7IZnD9LtUj3L0Dd:-Ki-tqPSl-Oa_hbil6vV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/516576e17958c707bd9c63a4ed4f56bcd7b1d601/.eslintrc.json#L15)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think you should add a NL at the end o all these files
</blockquote></details>

Done.

---

*[README.md, line 5 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-bSbZ60vjz5Q1gcix:-Ki-tmRiRc2jja3_ADgO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/516576e17958c707bd9c63a4ed4f56bcd7b1d601/README.md#L5)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Please add some description about what this component is here.
I think we should notice the user that is a mixin used in vaadin components and API could change without advise.
</blockquote></details>

Done.

---

*[README.md, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-Ki-bsePgP0PrybH849l:-Ki-tlkdfOn5_tBQJ_vm:b-896fix) ([raw file](https://github.com/vaadin/vaadin-control-state-mixin/blob/516576e17958c707bd9c63a4ed4f56bcd7b1d601/README.md#L24)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Some times URLs without ending are redirected to local folder. I think it's better to end the url with '/index.html'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 6 of 14 files at r1, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-control-state-mixin/1#-:-Ki0w-MCCOnHsUAdpjyU:b-uwkowd)*

**Pull request merged**
